<h2>Quiz 1 : Akses Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [59]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# print semua key yang ada di objek europe
print(europe.keys())
# print nilai dari key franche
print(europe['france'])

dict_keys(['spain', 'france', 'germany', 'norway'])
paris


Expected Output :

dict_keys(['spain', 'france', 'germany', 'norway'])

paris

<h2>Quiz 2 : Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [60]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma
europe.update({'itali':'roma'})

# cek apakah itali ada di dalam objek dictionary
print('itali' in europe)

True


Expected Output :
    
True

<h2>Quiz 3 : Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [61]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin
europe.update({'germany':'berlin'})

# remove australia dari europa
del europe['australia']

print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output :

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Quiz 4 : Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [62]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?
print(country['germany']['population'])

# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country.update({'indonesia':{'capital':'jakarta','population':250}})

print(country)

80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output :

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Quiz 5 : Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [63]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for k,v in country.items():
    print("Ibukota "+ str(k) +" adalah " + str(country[k]['capital']))  

Ibukota spain adalah madrid
Ibukota france adalah paris
Ibukota germany adalah berlin
Ibukota norway adalah oslo
Ibukota indonesia adalah jakarta


Expected Output :
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta

In [13]:
a=[2,3,5]
b=[3,4,5]
[x+y for x,y in zip(a,b)]

[5, 7, 10]

In [15]:
8>16 or 9 >20

False

In [16]:
[10]*5

[10, 10, 10, 10, 10]

In [17]:
sum([10, True, 3, False])

14

In [18]:
x = [[12, 32, 1], [2, 3, 4], [2, 5, 3]]; print(x[1][1]) 

3


In [19]:
x=1,2,10,5,21
x[4]

21

In [35]:
def find_type(**y):
    return type(y)
a='bala'
find_type(str(a))

TypeError: find_type() takes 0 positional arguments but 1 was given

In [38]:
y = print(float('6')) 
    
type(y)

6.0


NoneType

In [47]:
a={'ab':'cd','ef':'gh'}
a.items()

dict_items([('ab', 'cd'), ('ef', 'gh')])

In [48]:
a = [2,4,6,4]
b=[1,3,5,2]
print(sum(a[1:]+b[2:]))

21
